# This is a basic workflow to help you get started with Actions

name: PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Extracts PR from Head SHA
      - name: Find PR
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        run: |
          PR=$(curl https://api.github.com/search/issues?q=${{ github.event.workflow_run.head_sha }} |
          grep -Po "(?<=${{ github.event.workflow_run.repository.full_name }}\/pulls\/)\d*" | head -1)
          echo "PR=$PR" >> $GITHUB_ENV
          
      - name: Pull PR
        if: ${{ github.event.workflow_run.event == 'pull_request' && env.PR }}
        run: |
          rm spec/index.bs
          rm wgsl/index.bs
          wget -O spec/index.bs https://raw.githubusercontent.com/${{ github.event.workflow_run.head_repository.full_name }}/${{ github.event.workflow_run.head_sha }}/spec/index.bs
          wget -O wgsl/index.bs https://raw.githubusercontent.com/${{ github.event.workflow_run.head_repository.full_name }}/${{ github.event.workflow_run.head_sha }}/wgsl/index.bs
          
      - name: Init Firebase
        if: ${{ github.event.workflow_run.event == 'pull_request' && env.PR }}
        run: |
          cat << EOF >> .firebaserc
          {
            "projects": {
              "default": "gpuweb-prs"
            }
          }
          EOF
          cat << EOF >> firebase.json
          {
            "hosting": {
              "public": "out",
              "ignore": [
                "firebase.json",
                "**/.*",
                "**/node_modules/**"
              ]
            }
          }
          EOF
          cat .firebaserc
          cat firebase.json

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls
          ls spec
          ls wgsl
